# odin2 code generation from Petri nets ------------------------------------
# Generates odin2 DSL code for:
#   - ODE (continuous deterministic): deriv()
#   - DDE (continuous with delays):   deriv() + delay()
#   - Stochastic (discrete):          update() + Binomial()
#   - Discrete deterministic:         update() with Euler step

#' Generate odin2 code from a Petri net
#'
#' @param pn A Petri net ACSet (LabelledPetriNet or ReactionNet)
#' @param type Model type:
#'   - `"ode"`: continuous ODE with `deriv()`
#'   - `"dde"`: delay differential equation with `deriv()` + `delay()`
#'   - `"stochastic"`: discrete-time stochastic with `update()` + `Binomial()`
#'   - `"discrete"`: discrete-time deterministic Euler with `update()`
#' @param rate_style Currently only `"mass_action"` is implemented.
#'   `"custom"` is reserved and will error if requested.
#' @param delays Named list for DDE: maps transition names to delay specs.
#'   Each element is a list with `tau` (numeric delay time) and optionally
#'   `species` (character vector of which input species are delayed).
#' @param compare Optional named list mapping observed variables to
#'   distribution families (e.g., `list(cases = "Poisson")`)
#' @returns A character string of odin2 DSL code
#' @examples
#' sir <- labelled_petri_net(
#'   c("S", "I", "R"),
#'   inf = c("S", "I") %=>% c("I", "I"),
#'   rec = "I" %=>% "R"
#' )
#' # Generate ODE code
#' code <- pn_to_odin(sir, type = "ode")
#' cat(code)
#'
#' # Generate stochastic discrete-time code
#' code_stoch <- pn_to_odin(sir, type = "stochastic")
#' cat(code_stoch)
#' @export
pn_to_odin <- function(pn, type = c("ode", "dde", "stochastic", "discrete"),
                     rate_style = "mass_action", delays = NULL,
                     compare = NULL) {
  type <- match.arg(type)
  # Accept TypedPetriNet (extract underlying PN)
  if (S7::S7_inherits(pn, TypedPetriNet)) pn <- pn@pn
  snames <- species_names(pn)
  tnames <- transition_names(pn)
  ns <- length(snames)
  nt <- length(tnames)
  tm <- transition_matrices(pn)
  validate_petri_rate_style(rate_style)

  lines <- character()
  lines <- c(lines, "## Auto-generated by algebraicodin")
  lines <- c(lines, "")

  if (type == "ode") {
    lines <- c(lines, generate_ode_code(pn, snames, tnames, tm, rate_style))
  } else if (type == "dde") {
    if (is.null(delays) || length(delays) == 0L) {
      cli::cli_abort("DDE type requires {.arg delays} to be specified.")
    }
    validate_delay_specs(delays, tnames, snames)
    lines <- c(lines, generate_dde_code(pn, snames, tnames, tm, rate_style, delays))
  } else if (type == "stochastic") {
    validate_stochastic_petri(tm, tnames, context = "pn_to_odin(type = \"stochastic\")")
    lines <- c(lines, generate_stochastic_code(pn, snames, tnames, tm, rate_style))
  } else {
    lines <- c(lines, generate_discrete_code(pn, snames, tnames, tm, rate_style))
  }

  # Add comparison/likelihood code if requested
  lines <- c(lines, generate_compare_code(compare, "petri", type))

  paste(lines, collapse = "\n")
}

validate_petri_rate_style <- function(rate_style) {
  if (!identical(rate_style, "mass_action")) {
    cli::cli_abort(c(
      "Only {.val mass_action} is currently implemented for Petri net odin generation.",
      i = "Received {.code rate_style = {encodeString(rate_style, quote = '\"')}}.",
      i = "{.code rate_style = \"custom\"} is reserved for a future implementation."
    ))
  }
}

validate_delay_specs <- function(delays, tnames, snames) {
  unknown_transitions <- setdiff(names(delays), tnames)
  if (length(unknown_transitions) > 0L) {
    cli::cli_abort(c(
      "Unknown delayed transition name(s).",
      x = paste(unknown_transitions, collapse = ", "),
      i = "Valid transitions are: {paste(tnames, collapse = ', ')}."
    ))
  }

  for (tn in names(delays)) {
    dspec <- delays[[tn]]
    if (!is.list(dspec) || is.null(dspec$tau) || length(dspec$tau) != 1L ||
        !is.numeric(dspec$tau) || !is.finite(dspec$tau)) {
      cli::cli_abort("Delay spec for transition '{tn}' must contain a finite numeric `tau`.")
    }
    if (!is.null(dspec$species)) {
      unknown_species <- setdiff(dspec$species, snames)
      if (length(unknown_species) > 0L) {
        cli::cli_abort(c(
          "Unknown delayed species for transition '{tn}'.",
          x = paste(unknown_species, collapse = ", "),
          i = "Valid species are: {paste(snames, collapse = ', ')}."
        ))
      }
    }
  }
}

validate_stochastic_petri <- function(tm, tnames, context) {
  for (j in seq_along(tnames)) {
    if (any(tm$input[, j] > 1L)) {
      cli::cli_abort(c(
        "{.code {context}} does not currently support repeated self-inputs in stochastic transitions.",
        x = "Transition '{tnames[j]}' has input multiplicity greater than 1 for at least one species.",
        i = "Use deterministic code generation for this model, or refactor the transition."
      ))
    }
  }
}

generate_ode_code <- function(pn, snames, tnames, tm, rate_style) {
  ns <- length(snames)
  nt <- length(tnames)
  lines <- character()

  # Parameters (rate constants)
  lines <- c(lines, "## Parameters")
  for (j in seq_len(nt)) {
    lines <- c(lines, sprintf("%s <- parameter()", tnames[j]))
  }
  lines <- c(lines, "")

  # Initial conditions
  lines <- c(lines, "## Initial conditions")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("%s0 <- parameter()", snames[i]))
  }
  lines <- c(lines, "")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("initial(%s) <- %s0", snames[i], snames[i]))
  }
  lines <- c(lines, "")

  # Transition rates (mass action)
  lines <- c(lines, "## Transition rates")
  for (j in seq_len(nt)) {
    rate_expr <- mass_action_rate(snames, tm$input[, j], tnames[j])
    lines <- c(lines, sprintf("rate_%s <- %s", tnames[j], rate_expr))
  }
  lines <- c(lines, "")

  # Derivatives
  lines <- c(lines, "## Derivatives")
  for (i in seq_len(ns)) {
    terms <- character()
    for (j in seq_len(nt)) {
      net <- tm$stoichiometry[i, j]
      if (net != 0L) {
        if (net > 0L) {
          terms <- c(terms, if (net == 1L) sprintf("rate_%s", tnames[j])
                            else sprintf("%d * rate_%s", net, tnames[j]))
        } else {
          terms <- c(terms, if (net == -1L) sprintf("-rate_%s", tnames[j])
                            else sprintf("%d * rate_%s", net, tnames[j]))
        }
      }
    }
    if (length(terms) == 0L) terms <- "0"
    rhs <- paste(terms, collapse = " + ")
    rhs <- gsub("\\+ -", "- ", rhs)
    lines <- c(lines, sprintf("deriv(%s) <- %s", snames[i], rhs))
  }

  lines
}

generate_dde_code <- function(pn, snames, tnames, tm, rate_style, delays) {
  ns <- length(snames)
  nt <- length(tnames)
  lines <- character()

  # Parameters
  lines <- c(lines, "## Parameters")
  for (j in seq_len(nt)) {
    lines <- c(lines, sprintf("%s <- parameter()", tnames[j]))
  }
  lines <- c(lines, "")

  # Initial conditions
  lines <- c(lines, "## Initial conditions")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("%s0 <- parameter()", snames[i]))
  }
  lines <- c(lines, "")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("initial(%s) <- %s0", snames[i], snames[i]))
  }
  lines <- c(lines, "")

  # Delayed variables
  lines <- c(lines, "## Delayed variables")
  delayed_vars <- list()
  for (tn in names(delays)) {
    dspec <- delays[[tn]]
    tau <- dspec$tau
    delayed_species <- dspec$species
    if (is.null(delayed_species)) {
      # Delay all inputs to this transition
      j <- match(tn, tnames)
      input_sp <- which(tm$input[, j] > 0L)
      delayed_species <- snames[input_sp]
    }
    for (sp in delayed_species) {
      vname <- sprintf("%s_delayed_%s", sp, tn)
      if (!(vname %in% names(delayed_vars))) {
        lines <- c(lines, sprintf("%s <- delay(%s, %s)", vname, sp, tau))
        delayed_vars[[vname]] <- list(species = sp, transition = tn, tau = tau)
      }
    }
  }
  lines <- c(lines, "")

  # Transition rates (using delayed values where specified)
  lines <- c(lines, "## Transition rates")
  for (j in seq_len(nt)) {
    tn <- tnames[j]
    dspec <- delays[[tn]]
    terms <- tn
    for (i in seq_len(ns)) {
      if (tm$input[i, j] > 0L) {
        # Check if this species is delayed for this transition
        vname <- sprintf("%s_delayed_%s", snames[i], tn)
        sp_name <- if (!is.null(dspec) && vname %in% names(delayed_vars)) vname else snames[i]
        if (tm$input[i, j] == 1L) {
          terms <- paste0(terms, " * ", sp_name)
        } else {
          terms <- paste0(terms, " * ", sp_name, "^", tm$input[i, j])
        }
      }
    }
    lines <- c(lines, sprintf("rate_%s <- %s", tn, terms))
  }
  lines <- c(lines, "")

  # Derivatives (same as ODE)
  lines <- c(lines, "## Derivatives")
  for (i in seq_len(ns)) {
    terms <- stoich_to_terms(tm$stoichiometry[i, ], tnames)
    lines <- c(lines, sprintf("deriv(%s) <- %s", snames[i], terms))
  }

  lines
}

generate_discrete_code <- function(pn, snames, tnames, tm, rate_style) {
  ns <- length(snames)
  nt <- length(tnames)
  lines <- character()

  # Parameters
  lines <- c(lines, "## Parameters")
  for (j in seq_len(nt)) {
    lines <- c(lines, sprintf("%s <- parameter()", tnames[j]))
  }
  lines <- c(lines, "")

  # Initial conditions
  lines <- c(lines, "## Initial conditions")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("%s0 <- parameter()", snames[i]))
  }
  lines <- c(lines, "")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("initial(%s) <- %s0", snames[i], snames[i]))
  }
  lines <- c(lines, "")

  # Deterministic transition rates
  lines <- c(lines, "## Transition rates (deterministic Euler step)")
  for (j in seq_len(nt)) {
    rate_expr <- mass_action_rate(snames, tm$input[, j], tnames[j])
    lines <- c(lines, sprintf("rate_%s <- %s", tnames[j], rate_expr))
  }
  lines <- c(lines, "")

  # Update equations: u_{n+1} = u_n + dt * stoich * rates
  lines <- c(lines, "## Update equations")
  for (i in seq_len(ns)) {
    terms <- snames[i]
    for (j in seq_len(nt)) {
      net <- tm$stoichiometry[i, j]
      if (net != 0L) {
        if (net > 0L) {
          coeff <- if (net == 1L) "" else paste0(net, " * ")
          terms <- paste(terms, "+", paste0(coeff, "dt * rate_", tnames[j]))
        } else {
          coeff <- if (net == -1L) "" else paste0(-net, " * ")
          terms <- paste(terms, "-", paste0(coeff, "dt * rate_", tnames[j]))
        }
      }
    }
    lines <- c(lines, sprintf("update(%s) <- %s", snames[i], terms))
  }

  lines
}

# Helper: convert stoichiometry row to rate expression string
stoich_to_terms <- function(stoich_row, tnames) {
  terms <- character()
  for (j in seq_along(stoich_row)) {
    net <- stoich_row[j]
    if (net != 0L) {
      if (net > 0L) {
        terms <- c(terms, if (net == 1L) sprintf("rate_%s", tnames[j])
                          else sprintf("%d * rate_%s", net, tnames[j]))
      } else {
        terms <- c(terms, if (net == -1L) sprintf("-rate_%s", tnames[j])
                          else sprintf("%d * rate_%s", net, tnames[j]))
      }
    }
  }
  if (length(terms) == 0L) return("0")
  rhs <- paste(terms, collapse = " + ")
  gsub("\\+ -", "- ", rhs)
}

generate_stochastic_code <- function(pn, snames, tnames, tm, rate_style) {
  ns <- length(snames)
  nt <- length(tnames)
  lines <- character()

  # Parameters
  lines <- c(lines, "## Parameters")
  for (j in seq_len(nt)) {
    lines <- c(lines, sprintf("%s <- parameter()", tnames[j]))
  }
  lines <- c(lines, "")

  # Initial conditions
  lines <- c(lines, "## Initial conditions")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("%s0 <- parameter()", snames[i]))
  }
  lines <- c(lines, "")
  for (i in seq_len(ns)) {
    lines <- c(lines, sprintf("initial(%s) <- %s0", snames[i], snames[i]))
  }
  lines <- c(lines, "")

  # Transition probabilities and draws
  lines <- c(lines, "## Transition probabilities and draws")
  for (j in seq_len(nt)) {
    input_species <- which(tm$input[, j] > 0L)
    draw_name <- sprintf("n_%s", tnames[j])
    if (length(input_species) == 0L) {
      lines <- c(lines, sprintf("%s <- Poisson(%s * dt)", draw_name, tnames[j]))
    } else {
      rate_expr <- mass_action_hazard(snames, tm$input[, j], tnames[j])
      prob_name <- sprintf("p_%s", tnames[j])
      lines <- c(lines, sprintf("%s <- 1 - exp(-(%s) * dt)", prob_name, rate_expr))
      substrate <- snames[input_species[1]]
      lines <- c(lines, sprintf("%s <- Binomial(%s, %s)", draw_name, substrate, prob_name))
    }
  }
  lines <- c(lines, "")

  # Update equations
  lines <- c(lines, "## Update equations")
  for (i in seq_len(ns)) {
    terms <- snames[i]
    for (j in seq_len(nt)) {
      net <- tm$stoichiometry[i, j]
      if (net != 0L) {
        draw_name <- sprintf("n_%s", tnames[j])
        if (net > 0L) {
          terms <- paste(terms, "+", if (net == 1L) draw_name else paste(net, "*", draw_name))
        } else {
          terms <- paste(terms, "-", if (net == -1L) draw_name else paste(-net, "*", draw_name))
        }
      }
    }
    lines <- c(lines, sprintf("update(%s) <- %s", snames[i], terms))
  }

  lines
}

# Build mass-action rate expression: rate * x1^n1 * x2^n2 * ...
mass_action_rate <- function(snames, input_col, rate_name) {
  terms <- rate_name
  for (i in seq_along(input_col)) {
    if (input_col[i] == 1L) {
      terms <- paste0(terms, " * ", snames[i])
    } else if (input_col[i] > 1L) {
      terms <- paste0(terms, " * ", snames[i], "^", input_col[i])
    }
  }
  terms
}

# Build mass-action hazard (per-capita rate for stochastic)
mass_action_hazard <- function(snames, input_col, rate_name) {
  # For stochastic: the hazard is rate * (other inputs)
  # The substrate (first input) is handled by Binomial
  input_species <- which(input_col > 0L)
  if (length(input_species) <= 1L) return(rate_name)

  # Per-capita: divide out the substrate
  terms <- rate_name
  substrate <- input_species[1]
  for (idx in input_species[-1]) {
    if (input_col[idx] == 1L) {
      terms <- paste0(terms, " * ", snames[idx])
    } else {
      terms <- paste0(terms, " * ", snames[idx], "^", input_col[idx])
    }
  }
  terms
}

#' Generate odin2 code and return it as a callable odin_system generator
#'
#' If odin2 is available, this returns a function that when called creates
#' an odin system. Otherwise returns the code string.
#'
#' @inheritParams pn_to_odin
#' @returns A function that creates an odin system, or a code string
#' @examples
#' \donttest{
#' sir <- labelled_petri_net(
#'   c("S", "I", "R"),
#'   inf = c("S", "I") %=>% c("I", "I"),
#'   rec = "I" %=>% "R"
#' )
#' gen <- pn_to_odin_system(sir, type = "ode")
#' sys <- gen() # creates an odin2 system (requires odin2)
#' }
#' @export
pn_to_odin_system <- function(pn, type = c("ode", "dde", "stochastic", "discrete"),
                           rate_style = "mass_action", delays = NULL,
                           compare = NULL) {
  type <- match.arg(type)
  code <- pn_to_odin(pn, type = type, rate_style = rate_style,
                  delays = delays, compare = compare)

  if (requireNamespace("odin2", quietly = TRUE)) {
    function() odin2::odin(code)
  } else {
    cli::cli_warn("odin2 not available; returning code string")
    code
  }
}

# Backward-compatible aliases
#' @rdname pn_to_odin
#' @export
to_odin <- pn_to_odin

#' @rdname pn_to_odin_system
#' @export
to_odin_system <- pn_to_odin_system
